/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotDashboardDashboardRouteImport } from './routes/dashboard/dashboard'
import { Route as DotUsersUsersListUsersListRouteImport } from './routes/users/users-list/users-list'

const DotDashboardDashboardRoute = DotDashboardDashboardRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotUsersUsersListUsersListRoute =
  DotUsersUsersListUsersListRouteImport.update({
    id: '/users/list',
    path: '/users/list',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DotDashboardDashboardRoute
  '/users/list': typeof DotUsersUsersListUsersListRoute
}
export interface FileRoutesByTo {
  '/': typeof DotDashboardDashboardRoute
  '/users/list': typeof DotUsersUsersListUsersListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof DotDashboardDashboardRoute
  '/users/list': typeof DotUsersUsersListUsersListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/users/list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/users/list'
  id: '__root__' | '/' | '/users/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotDashboardDashboardRoute: typeof DotDashboardDashboardRoute
  DotUsersUsersListUsersListRoute: typeof DotUsersUsersListUsersListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DotDashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/list': {
      id: '/users/list'
      path: '/users/list'
      fullPath: '/users/list'
      preLoaderRoute: typeof DotUsersUsersListUsersListRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DotDashboardDashboardRoute: DotDashboardDashboardRoute,
  DotUsersUsersListUsersListRoute: DotUsersUsersListUsersListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
